[package]
name = "jux_rust"
version = "0.1.0"
authors = ["Qqwy/Wiebe-Marten Wijnja <w-m@wmcode.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
