<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jux</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\s*\[\s*$</string>
	<key>foldingStopMarker</key>
	<string>\]\s*$</string>
	<key>name</key>
	<string>Jux Syntax (Beta)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotation_start</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotation_end</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#integer</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.jux-beta_syntax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.jux-beta_syntax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *| +)((#).*\n?)</string>
		</dict>
		<key>definition</key>
		<dict>
			<key>begin</key>
			<string>"([a-zA-Z_][\w]*[?!]?)"</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jux-beta_syntax</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>support.constant.jux-beta_syntax</string>
			<key>end</key>
			<string>def</string>
			<key>name</key>
			<string>entity.other.function.jux-beta_syntax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotation_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotation_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_][\w]*[?!]?)</string>
			<key>name</key>
			<string>variable.language.jux-beta_syntax</string>
		</dict>
		<key>integer</key>
		<dict>
			<key>match</key>
			<string>([+-]?\d+)</string>
			<key>name</key>
			<string>constant.numeric.jux-beta_syntax</string>
		</dict>
		<key>quotation_end</key>
		<dict>
			<key>match</key>
			<string>(\])</string>
			<key>name</key>
			<string>keyword.control.quotation.end.jux-beta_syntax</string>
		</dict>
		<key>quotation_start</key>
		<dict>
			<key>match</key>
			<string>(\[)</string>
			<key>name</key>
			<string>keyword.control.quotation.start.jux-beta_syntax</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.jux-beta_syntax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\.)</string>
					<key>name</key>
					<string>constant.character.escape.jux-beta_syntax</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jux-beta_syntax</string>
	<key>uuid</key>
	<string>c2678932-0739-4006-bb20-30e38fe41dea</string>
</dict>
</plist>
